# Generated by Django 4.2.4 on 2023-09-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductLst',
            new_name='Product',
        ),
    ]
