# Generated by Django 4.2.4 on 2023-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_product_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.FloatField(default=3.0),
        ),
    ]
