# Generated by Django 4.2.4 on 2023-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_product_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgurl',
            field=models.CharField(default=None, max_length=2480, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(default=None, max_length=59248, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=2480),
        ),
    ]
